[eslint] linting fixed after adding lint rules
Cubeseed/Frontend pull request #33
Opened 2023-09-21 09:19 UTC by abu-hasib

2023-09-26 18:58 UTC, abu-hasib commented
@MimaoQiuQiu these are fixes for the lint error when i added lining. Please check and approve.

2023-11-06 22:32 UTC, mihrab34 commented
@abu-hasib  great work. I did notice that you have other changes apart from the eslint and pre-husky commit.

2023-11-06 22:33 UTC, mihrab34 commented on cubeseed_login/components/create-invoice.tsx
> +import { DashboardHeading } from "./header"
Some of these changes could have been made in another PR or write clear commit messages for them so it's easily trackable.

2023-11-06 22:56 UTC, mihrab34 requested changes
can you re-arrange some of the components you added to the `cubeseed_login/components` folder and move it into the` src/components`
Having them in different places makes it confusing to review

2023-11-08 22:29 UTC, mihrab34 reviewed
We can just open a new issue for the folder restructure

2023-11-08 22:30 UTC, mihrab34 approved these changes

2023-11-08 22:30 UTC, merged

2023-11-08 23:08 UTC, abu-hasib commented
Not really, the app uses router app